package com.bawei.dengxianchao2020218.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dengxianchao2020218.dao.MyDao;

import com.bawei.dengxianchao2020218.database.MyDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myDaoDaoConfig;

    private final MyDaoDao myDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myDaoDaoConfig = daoConfigMap.get(MyDaoDao.class).clone();
        myDaoDaoConfig.initIdentityScope(type);

        myDaoDao = new MyDaoDao(myDaoDaoConfig, this);

        registerDao(MyDao.class, myDaoDao);
    }
    
    public void clear() {
        myDaoDaoConfig.clearIdentityScope();
    }

    public MyDaoDao getMyDaoDao() {
        return myDaoDao;
    }

}
