package com.bawei.dengxianchao2020218.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.dengxianchao2020218.dao.MyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_DAO".
*/
public class MyDaoDao extends AbstractDao<MyDao, Void> {

    public static final String TABLENAME = "MY_DAO";

    /**
     * Properties of entity MyDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Pic = new Property(0, String.class, "pic", false, "PIC");
    }


    public MyDaoDao(DaoConfig config) {
        super(config);
    }
    
    public MyDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_DAO\" (" + //
                "\"PIC\" TEXT);"); // 0: pic
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyDao entity) {
        stmt.clearBindings();
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(1, pic);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyDao entity) {
        stmt.clearBindings();
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(1, pic);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MyDao readEntity(Cursor cursor, int offset) {
        MyDao entity = new MyDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // pic
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyDao entity, int offset) {
        entity.setPic(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MyDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MyDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(MyDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
