package com.bawei.jiaqizuoye2020_03_14.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.jiaqizuoye2020_03_14.MyGwc;

import com.bawei.jiaqizuoye2020_03_14.database.MyGwcDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myGwcDaoConfig;

    private final MyGwcDao myGwcDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myGwcDaoConfig = daoConfigMap.get(MyGwcDao.class).clone();
        myGwcDaoConfig.initIdentityScope(type);

        myGwcDao = new MyGwcDao(myGwcDaoConfig, this);

        registerDao(MyGwc.class, myGwcDao);
    }
    
    public void clear() {
        myGwcDaoConfig.clearIdentityScope();
    }

    public MyGwcDao getMyGwcDao() {
        return myGwcDao;
    }

}
