package com.bawei.week_0104.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dao.Myfendao;
import com.bawei.dao.MyXiangdao;

import com.bawei.week_0104.database.MyfendaoDao;
import com.bawei.week_0104.database.MyXiangdaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myfendaoDaoConfig;
    private final DaoConfig myXiangdaoDaoConfig;

    private final MyfendaoDao myfendaoDao;
    private final MyXiangdaoDao myXiangdaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myfendaoDaoConfig = daoConfigMap.get(MyfendaoDao.class).clone();
        myfendaoDaoConfig.initIdentityScope(type);

        myXiangdaoDaoConfig = daoConfigMap.get(MyXiangdaoDao.class).clone();
        myXiangdaoDaoConfig.initIdentityScope(type);

        myfendaoDao = new MyfendaoDao(myfendaoDaoConfig, this);
        myXiangdaoDao = new MyXiangdaoDao(myXiangdaoDaoConfig, this);

        registerDao(Myfendao.class, myfendaoDao);
        registerDao(MyXiangdao.class, myXiangdaoDao);
    }
    
    public void clear() {
        myfendaoDaoConfig.clearIdentityScope();
        myXiangdaoDaoConfig.clearIdentityScope();
    }

    public MyfendaoDao getMyfendaoDao() {
        return myfendaoDao;
    }

    public MyXiangdaoDao getMyXiangdaoDao() {
        return myXiangdaoDao;
    }

}
