package com.bawei.week_0104.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.dao.Myfendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MYFENDAO".
*/
public class MyfendaoDao extends AbstractDao<Myfendao, Void> {

    public static final String TABLENAME = "MYFENDAO";

    /**
     * Properties of entity Myfendao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Fendao = new Property(0, String.class, "fendao", false, "FENDAO");
    }


    public MyfendaoDao(DaoConfig config) {
        super(config);
    }
    
    public MyfendaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MYFENDAO\" (" + //
                "\"FENDAO\" TEXT);"); // 0: fendao
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MYFENDAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Myfendao entity) {
        stmt.clearBindings();
 
        String fendao = entity.getFendao();
        if (fendao != null) {
            stmt.bindString(1, fendao);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Myfendao entity) {
        stmt.clearBindings();
 
        String fendao = entity.getFendao();
        if (fendao != null) {
            stmt.bindString(1, fendao);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Myfendao readEntity(Cursor cursor, int offset) {
        Myfendao entity = new Myfendao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // fendao
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Myfendao entity, int offset) {
        entity.setFendao(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Myfendao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Myfendao entity) {
        return null;
    }

    @Override
    public boolean hasKey(Myfendao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
