package com.bawei.dengxianchao20200316.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dengxianchao20200316.MyShop;

import com.bawei.dengxianchao20200316.database.MyShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myShopDaoConfig;

    private final MyShopDao myShopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myShopDaoConfig = daoConfigMap.get(MyShopDao.class).clone();
        myShopDaoConfig.initIdentityScope(type);

        myShopDao = new MyShopDao(myShopDaoConfig, this);

        registerDao(MyShop.class, myShopDao);
    }
    
    public void clear() {
        myShopDaoConfig.clearIdentityScope();
    }

    public MyShopDao getMyShopDao() {
        return myShopDao;
    }

}
