package com.bawei.dengxianchao20200106.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dengxianchao20200106.Mybean;

import com.bawei.dengxianchao20200106.database.MybeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mybeanDaoConfig;

    private final MybeanDao mybeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mybeanDaoConfig = daoConfigMap.get(MybeanDao.class).clone();
        mybeanDaoConfig.initIdentityScope(type);

        mybeanDao = new MybeanDao(mybeanDaoConfig, this);

        registerDao(Mybean.class, mybeanDao);
    }
    
    public void clear() {
        mybeanDaoConfig.clearIdentityScope();
    }

    public MybeanDao getMybeanDao() {
        return mybeanDao;
    }

}
